config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/Pre-Trip'

    root "pages#home"
    get "about" => "pages#about"
    get "itinerary" => "pages#itinerary"
    get "pretrip" => "pages#Pre-Trip"
    

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
    
  def about 
  end
   
  def itinerary 
  end   
    
  def pretrip 
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
   <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
         <img alt="Brand" src="images/afro_logo.jpg" class="img-responsive">
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Itinerary", itinerary_path %></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Guides <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Europe</a></li>
            <li><a href="#">Southeast Asia</a></li>
            <li><a href="#">Central America</a></li>
            <li class="divider"></li>
            <li><%= link_to "Pretrip", pretrip_path %></li>
            <li class="divider"></li>
            <li><a href="#">Budget</a></li>
          </ul>
        </li>
      </ul>
      <ul>   
        <form class="navbar-form navbar-right" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
      </form>
     </ul> 
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KesitoandfroCom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
</head>
<body>
    
    <%= render 'layouts/header' %>
    <div class="container-fluid">
        <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
        <% end %>
        <%= yield %>
    </div>
</body>
</html>

app/views/pages/Pre-Trip.html.erb
<h1>Pre-Trip</h1>
<p>Things to Plan</p>

app/views/pages/about.html.erb
<div class="container">
<h1>About Me</h1> 
    <p class="text-justify"> Hello! My name is Kesi. Thanks for stopping by kesitoandfro.com. I created this website so that my friends and family can <strong> Follow The Fro</strong> (a.k.a - keep them updated on my Global Journey).  Feel free to check out my blog, pictures, and travel guides!      </p>

    <h5><strong>W</strong>harton 
        <small>Where I started</small> 
    </h5>
    
    <h5 class="text-center"><strong>W</strong>all Street 
        <small>Where I Am</small>
    </h5>
    
    <h5 class="text-right">The <strong>W</strong>orld 
        <small> My Future </small>
    </h5>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
    <h1>Kesi To and Fro</h1>
    <p>Follow me on my adventures around the world.
        <br>
        <br><%= link_to "Click for Email Updates", new_user_registration_path, class:"btn btn-primary btn-lg"%>
        </br>
        </br>
    </p>
</div>

<div class="boxed">
</div>

app/views/pages/itinerary.html.erb
<h1> My Year Long Itinerary</h1>